defmodule WalkieTalkieWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :walkie_talkie

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_walkie_talkie_key",
    signing_salt: "2qYbyOUf",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
 plug Plug.Static,
  at: "/",
  from: :walkie_talkie,
  gzip: not code_reloading?,
  only: ~w(css js images uploads index.html favicon.ico robots.txt),
  raise_on_missing_only: code_reloading?

  # plug Plug.Static,
  #  at: "/",
  #  from: :walkie_talkie,
  #  gzip: not code_reloading?,
  #  only: WalkieTalkieWeb.static_paths(),
  #  raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :walkie_talkie
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,

    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

    # CORS manual para permitir peticiones desde cualquier frontend
  defp put_cors_headers(conn, _opts) do
    conn
    |> Plug.Conn.put_resp_header("access-control-allow-origin", "*")
    |> Plug.Conn.put_resp_header("access-control-allow-methods", "GET, POST, PUT, DELETE, OPTIONS, PATCH")
    |> Plug.Conn.put_resp_header("access-control-allow-headers", "content-type, authorization, accept")
  end

  plug :put_cors_headers
  plug WalkieTalkieWeb.Router

end
